<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="Data_Save" Id="{c5b6b376-ac25-4e52-bef8-9156169fe1cc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Data_Save
VAR
	IntervalTON     : TON;
    rtrigInterval   : R_TRIG;
    fbWritePersist  : FB_WritePersistentData;



END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Data_Save">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>