<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="Axis01_Interlock" Id="{1a2871bf-aa4d-4f83-9338-80c18a49dc56}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Axis01_Interlock
VAR
//System_Bit
	Always_ON	:	BOOL	:=TRUE	;//상시 ON 
	Always_OFF	:	BOOL	:=FALSE	;//상시 OFF
END_VAR
]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Ld"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"EXECUTE"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">2120L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"Always_On"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">2103L</v>
                          </o>
                          <v n="Id">2102L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">None</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <o n="STSnippet" t="STSnippet">
                        <o n="STSnippet" t="STImplementationObject">
                          <o n="TextDocument" t="TextDocument">
                            <a n="TextLines" cet="TextLine">
                              <o>
                                <v n="Id">2121L</v>
                                <n n="Tag" />
                                <v n="Text">"IF (GVL_Axis02.Real_Position &lt;= 55.0) THEN"</v>
                              </o>
                              <o>
                                <v n="Id">2122L</v>
                                <n n="Tag" />
                                <v n="Text">"	GVL_Axis01.Interlock := TRUE;"</v>
                              </o>
                              <o>
                                <v n="Id">2123L</v>
                                <n n="Tag" />
                                <v n="Text">"END_IF"</v>
                              </o>
                              <o>
                                <v n="Id">2124L</v>
                                <n n="Tag" />
                                <v n="Text">"IF (GVL_Axis02.Real_Position &gt;= 55.0) THEN"</v>
                              </o>
                              <o>
                                <v n="Id">2125L</v>
                                <n n="Tag" />
                                <v n="Text">"	IF GVL_Axis01.Selected_Position_Data"</v>
                              </o>
                              <o>
                                <v n="Id">2126L</v>
                                <n n="Tag" />
                                <v n="Text">"&gt; 0.0 THEN"</v>
                              </o>
                              <o>
                                <v n="Id">2127L</v>
                                <n n="Tag" />
                                <v n="Text">"		GVL_Axis01.Interlock := True;"</v>
                              </o>
                              <o>
                                <v n="Id">2128L</v>
                                <n n="Tag" />
                                <v n="Text">"	END_IF"</v>
                              </o>
                              <o>
                                <v n="Id">2111L</v>
                                <n n="Tag" />
                                <v n="Text">"END_IF"</v>
                              </o>
                            </a>
                          </o>
                        </o>
                        <v n="Id">2129L</v>
                      </o>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">true</v>
                      <v n="Id">2130L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">8L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" />
                  <l2 n="Connectors" />
                  <v n="Id">5L</v>
                </o>
              </l2>
              <v n="BranchCounter">0</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
            <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
            <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
            <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
            <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
            <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
            <Type n="STImplementationObject">{3b83b776-fb25-43b8-99f2-3c507c9143fc}</Type>
            <Type n="String">System.String</Type>
            <Type n="STSnippet">{b2131366-6917-4304-87a9-64c0585560a8}</Type>
            <Type n="TextDocument">{f3878285-8e4f-490b-bb1b-9acbb7eb04db}</Type>
            <Type n="TextLine">{a5de0b0b-1cb5-4913-ac21-9d70293ec00d}</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
  </POU>
</TcPlcObject>