<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="Axis02_Interlock" Id="{42d17d02-c8f5-405b-a8b7-936db7d763bc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Axis02_Interlock
VAR
	Always_ON	:	BOOL	:=TRUE	;//상시 ON 
	Always_OFF	:	BOOL	:=FALSE	;//상시 OFF
END_VAR
]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Ld"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"EXECUTE"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">6867L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeBox">
                        <o>
                          <v n="BoxType">"EXECUTE"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">6835L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems">
                              <n />
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"Always_On"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">6685L</v>
                              </o>
                              <v n="Id">6684L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>EN</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>ENO</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">None</v>
                          <v n="EN">true</v>
                          <v n="ENO">true</v>
                          <o n="STSnippet" t="STSnippet">
                            <o n="STSnippet" t="STImplementationObject">
                              <o n="TextDocument" t="TextDocument">
                                <a n="TextLines" cet="TextLine">
                                  <o>
                                    <v n="Id">6884L</v>
                                    <n n="Tag" />
                                    <v n="Text">"IF (GVL_Axis02.Home_Position_Data &gt; 55.0) THEN"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6885L</v>
                                    <n n="Tag" />
                                    <v n="Text">"    "</v>
                                  </o>
                                  <o>
                                    <v n="Id">6886L</v>
                                    <n n="Tag" />
                                    <v n="Text">"    IF (GVL_Axis01.Real_Position &gt; 0.0) AND"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6887L</v>
                                    <n n="Tag" />
                                    <v n="Text">"       (GVL_Axis04.Real_Position &lt; 15.1) AND"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6888L</v>
                                    <n n="Tag" />
                                    <v n="Text">"       (GVL_Axis03.Real_Position &gt;= 12.1) AND (GVL_Axis03.Real_Position &lt;= 18.1) AND"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6889L</v>
                                    <n n="Tag" />
                                    <v n="Text">"       (GVL_Axis05.Real_Position &gt;= -2.7) AND (GVL_Axis05.Real_Position &lt;= 2.3) THEN"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6890L</v>
                                    <n n="Tag" />
                                    <v n="Text">""</v>
                                  </o>
                                  <o>
                                    <v n="Id">6891L</v>
                                    <n n="Tag" />
                                    <v n="Text">"        GVL_Axis02.Home_Pos_Interlock := TRUE;"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6892L</v>
                                    <n n="Tag" />
                                    <v n="Text">"    ELSE"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6893L</v>
                                    <n n="Tag" />
                                    <v n="Text">"        GVL_Axis02.Home_Pos_Interlock := FALSE;"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6894L</v>
                                    <n n="Tag" />
                                    <v n="Text">"    END_IF;"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6895L</v>
                                    <n n="Tag" />
                                    <v n="Text">"ELSE"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6896L</v>
                                    <n n="Tag" />
                                    <v n="Text">"    GVL_Axis02.Home_Pos_Interlock := TRUE;"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6897L</v>
                                    <n n="Tag" />
                                    <v n="Text">""</v>
                                  </o>
                                  <o>
                                    <v n="Id">6806L</v>
                                    <n n="Tag" />
                                    <v n="Text">"END_IF;"</v>
                                  </o>
                                </a>
                              </o>
                            </o>
                            <v n="Id">6850L</v>
                          </o>
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">true</v>
                          <v n="Id">6851L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">None</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <o n="STSnippet" t="STSnippet">
                        <o n="STSnippet" t="STImplementationObject">
                          <o n="TextDocument" t="TextDocument">
                            <a n="TextLines" cet="TextLine">
                              <o>
                                <v n="Id">6868L</v>
                                <n n="Tag" />
                                <v n="Text">"IF (GVL_Axis02.Wait_Position_Data &gt; 55.0) THEN"</v>
                              </o>
                              <o>
                                <v n="Id">6869L</v>
                                <n n="Tag" />
                                <v n="Text">"    "</v>
                              </o>
                              <o>
                                <v n="Id">6870L</v>
                                <n n="Tag" />
                                <v n="Text">"    IF (GVL_Axis01.Real_Position &gt; 0.0) AND"</v>
                              </o>
                              <o>
                                <v n="Id">6871L</v>
                                <n n="Tag" />
                                <v n="Text">"       (GVL_Axis04.Real_Position &lt; 15.1) AND"</v>
                              </o>
                              <o>
                                <v n="Id">6872L</v>
                                <n n="Tag" />
                                <v n="Text">"       (GVL_Axis03.Real_Position &gt;= 12.1) AND (GVL_Axis03.Real_Position &lt;= 18.1) AND"</v>
                              </o>
                              <o>
                                <v n="Id">6873L</v>
                                <n n="Tag" />
                                <v n="Text">"       (GVL_Axis05.Real_Position &gt;= -2.7) AND (GVL_Axis05.Real_Position &lt;= 2.3) THEN"</v>
                              </o>
                              <o>
                                <v n="Id">6874L</v>
                                <n n="Tag" />
                                <v n="Text">""</v>
                              </o>
                              <o>
                                <v n="Id">6875L</v>
                                <n n="Tag" />
                                <v n="Text">"        GVL_Axis02.Wait_Pos_Interlock := TRUE;"</v>
                              </o>
                              <o>
                                <v n="Id">6876L</v>
                                <n n="Tag" />
                                <v n="Text">"    ELSE"</v>
                              </o>
                              <o>
                                <v n="Id">6877L</v>
                                <n n="Tag" />
                                <v n="Text">"        GVL_Axis02.Wait_Pos_Interlock := FALSE;"</v>
                              </o>
                              <o>
                                <v n="Id">6878L</v>
                                <n n="Tag" />
                                <v n="Text">"    END_IF;"</v>
                              </o>
                              <o>
                                <v n="Id">6879L</v>
                                <n n="Tag" />
                                <v n="Text">"ELSE"</v>
                              </o>
                              <o>
                                <v n="Id">6880L</v>
                                <n n="Tag" />
                                <v n="Text">"    GVL_Axis02.Wait_Pos_Interlock := TRUE;"</v>
                              </o>
                              <o>
                                <v n="Id">6881L</v>
                                <n n="Tag" />
                                <v n="Text">""</v>
                              </o>
                              <o>
                                <v n="Id">6852L</v>
                                <n n="Tag" />
                                <v n="Text">"END_IF;"</v>
                              </o>
                            </a>
                          </o>
                        </o>
                        <v n="Id">6882L</v>
                      </o>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">true</v>
                      <v n="Id">6883L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">13L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"EXECUTE"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">6913L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeBox">
                        <o>
                          <v n="BoxType">"EXECUTE"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">6973L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems">
                              <n />
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"Always_On"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">6722L</v>
                              </o>
                              <v n="Id">6721L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>EN</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>ENO</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">None</v>
                          <v n="EN">true</v>
                          <v n="ENO">true</v>
                          <o n="STSnippet" t="STSnippet">
                            <o n="STSnippet" t="STImplementationObject">
                              <o n="TextDocument" t="TextDocument">
                                <a n="TextLines" cet="TextLine">
                                  <o>
                                    <v n="Id">6974L</v>
                                    <n n="Tag" />
                                    <v n="Text">"IF (GVL_Axis02.Target_Position_Data &gt; 55.0) THEN"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6975L</v>
                                    <n n="Tag" />
                                    <v n="Text">"    "</v>
                                  </o>
                                  <o>
                                    <v n="Id">6976L</v>
                                    <n n="Tag" />
                                    <v n="Text">"    IF (GVL_Axis01.Real_Position &gt; 0.0) AND"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6977L</v>
                                    <n n="Tag" />
                                    <v n="Text">"       (GVL_Axis04.Real_Position &lt; 15.1) AND"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6978L</v>
                                    <n n="Tag" />
                                    <v n="Text">"       (GVL_Axis03.Real_Position &gt;= 12.1) AND (GVL_Axis03.Real_Position &lt;= 18.1) AND"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6979L</v>
                                    <n n="Tag" />
                                    <v n="Text">"       (GVL_Axis05.Real_Position &gt;= -2.7) AND (GVL_Axis05.Real_Position &lt;= 2.3) THEN"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6980L</v>
                                    <n n="Tag" />
                                    <v n="Text">""</v>
                                  </o>
                                  <o>
                                    <v n="Id">6981L</v>
                                    <n n="Tag" />
                                    <v n="Text">"        GVL_Axis02.Target_Pos_Interlock := TRUE;"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6982L</v>
                                    <n n="Tag" />
                                    <v n="Text">"    ELSE"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6983L</v>
                                    <n n="Tag" />
                                    <v n="Text">"        GVL_Axis02.Target_Pos_Interlock := FALSE;"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6984L</v>
                                    <n n="Tag" />
                                    <v n="Text">"    END_IF;"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6985L</v>
                                    <n n="Tag" />
                                    <v n="Text">"ELSE"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6986L</v>
                                    <n n="Tag" />
                                    <v n="Text">"    GVL_Axis02.Target_Pos_Interlock := TRUE;"</v>
                                  </o>
                                  <o>
                                    <v n="Id">6987L</v>
                                    <n n="Tag" />
                                    <v n="Text">""</v>
                                  </o>
                                  <o>
                                    <v n="Id">6944L</v>
                                    <n n="Tag" />
                                    <v n="Text">"END_IF;"</v>
                                  </o>
                                </a>
                              </o>
                            </o>
                            <v n="Id">6988L</v>
                          </o>
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">true</v>
                          <v n="Id">6989L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">None</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <o n="STSnippet" t="STSnippet">
                        <o n="STSnippet" t="STImplementationObject">
                          <o n="TextDocument" t="TextDocument">
                            <a n="TextLines" cet="TextLine">
                              <o>
                                <v n="Id">6959L</v>
                                <n n="Tag" />
                                <v n="Text">"IF (GVL_Axis02.Work_End_Position_Data &gt; 55.0) THEN"</v>
                              </o>
                              <o>
                                <v n="Id">6960L</v>
                                <n n="Tag" />
                                <v n="Text">"    "</v>
                              </o>
                              <o>
                                <v n="Id">6961L</v>
                                <n n="Tag" />
                                <v n="Text">"    IF (GVL_Axis01.Real_Position &gt; 0.0) AND"</v>
                              </o>
                              <o>
                                <v n="Id">6962L</v>
                                <n n="Tag" />
                                <v n="Text">"       (GVL_Axis04.Real_Position &lt; 15.1) AND"</v>
                              </o>
                              <o>
                                <v n="Id">6963L</v>
                                <n n="Tag" />
                                <v n="Text">"       (GVL_Axis03.Real_Position &gt;= 12.1) AND (GVL_Axis03.Real_Position &lt;= 18.1) AND"</v>
                              </o>
                              <o>
                                <v n="Id">6964L</v>
                                <n n="Tag" />
                                <v n="Text">"       (GVL_Axis05.Real_Position &gt;= -2.7) AND (GVL_Axis05.Real_Position &lt;= 2.3) THEN"</v>
                              </o>
                              <o>
                                <v n="Id">6965L</v>
                                <n n="Tag" />
                                <v n="Text">""</v>
                              </o>
                              <o>
                                <v n="Id">6966L</v>
                                <n n="Tag" />
                                <v n="Text">"        GVL_Axis02.Work_End_Pos_Interlock := TRUE;"</v>
                              </o>
                              <o>
                                <v n="Id">6967L</v>
                                <n n="Tag" />
                                <v n="Text">"    ELSE"</v>
                              </o>
                              <o>
                                <v n="Id">6968L</v>
                                <n n="Tag" />
                                <v n="Text">"        GVL_Axis02.Work_End_Pos_Interlock := FALSE;"</v>
                              </o>
                              <o>
                                <v n="Id">6969L</v>
                                <n n="Tag" />
                                <v n="Text">"    END_IF;"</v>
                              </o>
                              <o>
                                <v n="Id">6970L</v>
                                <n n="Tag" />
                                <v n="Text">"ELSE"</v>
                              </o>
                              <o>
                                <v n="Id">6971L</v>
                                <n n="Tag" />
                                <v n="Text">"    GVL_Axis02.Work_End_Pos_Interlock := TRUE;"</v>
                              </o>
                              <o>
                                <v n="Id">6972L</v>
                                <n n="Tag" />
                                <v n="Text">""</v>
                              </o>
                              <o>
                                <v n="Id">6898L</v>
                                <n n="Tag" />
                                <v n="Text">"END_IF;"</v>
                              </o>
                            </a>
                          </o>
                        </o>
                        <v n="Id">6928L</v>
                      </o>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">true</v>
                      <v n="Id">6929L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">6686L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"EXECUTE"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">7088L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeBox">
                        <o>
                          <v n="BoxType">"EXECUTE"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">6733L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems">
                              <n />
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeBox">
                            <o>
                              <v n="BoxType">"EXECUTE"</v>
                              <o n="Instance" t="Operand">
                                <n n="Operand" />
                                <v n="Type">""</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">true</v>
                                <v n="Id">7135L</v>
                              </o>
                              <o n="OutputItems" t="OutputItemList">
                                <l2 n="OutputItems">
                                  <n />
                                </l2>
                              </o>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <n n="InputFlags" />
                              <l2 n="InputItems" cet="BoxTreeOperand">
                                <o>
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"Always_On"</v>
                                    <v n="Type">"BOOL"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">6753L</v>
                                  </o>
                                  <v n="Id">6752L</v>
                                </o>
                              </l2>
                              <o n="InputParam" t="ParamList">
                                <l2 n="Names" cet="String">
                                  <v>EN</v>
                                </l2>
                                <l2 n="Types" cet="String">
                                  <v>BOOL</v>
                                </l2>
                              </o>
                              <o n="OutputParam" t="ParamList">
                                <l2 n="Names" cet="String">
                                  <v>ENO</v>
                                </l2>
                                <l2 n="Types" cet="String">
                                  <v>BOOL</v>
                                </l2>
                              </o>
                              <v n="CallType" t="Operator">None</v>
                              <v n="EN">true</v>
                              <v n="ENO">true</v>
                              <o n="STSnippet" t="STSnippet">
                                <o n="STSnippet" t="STImplementationObject">
                                  <o n="TextDocument" t="TextDocument">
                                    <a n="TextLines" cet="TextLine">
                                      <o>
                                        <v n="Id">7136L</v>
                                        <n n="Tag" />
                                        <v n="Text">"IF (GVL_Axis02.Real_Position &gt; 55.0) THEN"</v>
                                      </o>
                                      <o>
                                        <v n="Id">7137L</v>
                                        <n n="Tag" />
                                        <v n="Text">"	GVL_Axis02.Home_ORG_Interlock	:=	TRUE ;"</v>
                                      </o>
                                      <o>
                                        <v n="Id">7138L</v>
                                        <n n="Tag" />
                                        <v n="Text">"ELSE"</v>
                                      </o>
                                      <o>
                                        <v n="Id">7139L</v>
                                        <n n="Tag" />
                                        <v n="Text">"	IF	GVL_Axis03.Home_Position OR "</v>
                                      </o>
                                      <o>
                                        <v n="Id">7140L</v>
                                        <n n="Tag" />
                                        <v n="Text">"		(GVL_Axis03.Real_Position &gt;= 12.6) AND"</v>
                                      </o>
                                      <o>
                                        <v n="Id">7141L</v>
                                        <n n="Tag" />
                                        <v n="Text">"		(GVL_Axis03.Real_Position &lt;= 18.6) THEN"</v>
                                      </o>
                                      <o>
                                        <v n="Id">7142L</v>
                                        <n n="Tag" />
                                        <v n="Text">"	GVL_Axis02.Home_ORG_Interlock	:=	 TRUE	;"</v>
                                      </o>
                                      <o>
                                        <v n="Id">7143L</v>
                                        <n n="Tag" />
                                        <v n="Text">"	END_IF"</v>
                                      </o>
                                      <o>
                                        <v n="Id">7115L</v>
                                        <n n="Tag" />
                                        <v n="Text">"END_IF"</v>
                                      </o>
                                    </a>
                                  </o>
                                </o>
                                <v n="Id">7144L</v>
                              </o>
                              <v n="ContainsExtensibleInputs">false</v>
                              <v n="ProvidesSTSnippet">true</v>
                              <v n="Id">7145L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>EN</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>ENO</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">None</v>
                          <v n="EN">true</v>
                          <v n="ENO">true</v>
                          <o n="STSnippet" t="STSnippet">
                            <o n="STSnippet" t="STImplementationObject">
                              <o n="TextDocument" t="TextDocument">
                                <a n="TextLines" cet="TextLine">
                                  <o>
                                    <v n="Id">7130L</v>
                                    <n n="Tag" />
                                    <v n="Text">"IF (GVL_Axis01.Real_Position &gt; 32.9) AND (GVL_Axis03.Real_Position &gt;= -4) AND (GVL_Axis03.Real_Position &lt;= 34)THEN"</v>
                                  </o>
                                  <o>
                                    <v n="Id">7131L</v>
                                    <n n="Tag" />
                                    <v n="Text">"	GVL_Calibration.Calibration_Pos_Interlock := TRUE;"</v>
                                  </o>
                                  <o>
                                    <v n="Id">7132L</v>
                                    <n n="Tag" />
                                    <v n="Text">"ELSE"</v>
                                  </o>
                                  <o>
                                    <v n="Id">7133L</v>
                                    <n n="Tag" />
                                    <v n="Text">"    GVL_Calibration.Calibration_Pos_Interlock := FALSE;"</v>
                                  </o>
                                  <o>
                                    <v n="Id">7134L</v>
                                    <n n="Tag" />
                                    <v n="Text">"END_IF;"</v>
                                  </o>
                                  <o>
                                    <v n="Id">5780L</v>
                                    <n n="Tag" />
                                    <v n="Text">""</v>
                                  </o>
                                </a>
                              </o>
                            </o>
                            <v n="Id">6739L</v>
                          </o>
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">true</v>
                          <v n="Id">6740L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">None</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <o n="STSnippet" t="STSnippet">
                        <o n="STSnippet" t="STImplementationObject">
                          <o n="TextDocument" t="TextDocument">
                            <a n="TextLines" cet="TextLine">
                              <o>
                                <v n="Id">7124L</v>
                                <n n="Tag" />
                                <v n="Text">"IF (GVL_Calibration.Calibration_Pos_Interlock = TRUE) AND (GVL_Axis02.Home_Pos_Interlock = TRUE)"</v>
                              </o>
                              <o>
                                <v n="Id">7125L</v>
                                <n n="Tag" />
                                <v n="Text">"AND (GVL_Axis02.Wait_Pos_Interlock = TRUE) AND (GVL_Axis02.Target_Pos_Interlock = TRUE) AND (GVL_Axis02.Work_End_Pos_Interlock = TRUE) THEN"</v>
                              </o>
                              <o>
                                <v n="Id">7126L</v>
                                <n n="Tag" />
                                <v n="Text">"	GVL_Axis02.Interlock := TRUE;"</v>
                              </o>
                              <o>
                                <v n="Id">7127L</v>
                                <n n="Tag" />
                                <v n="Text">"	ELSE"</v>
                              </o>
                              <o>
                                <v n="Id">7128L</v>
                                <n n="Tag" />
                                <v n="Text">"	GVL_Axis02.Interlock := FALSE;	"</v>
                              </o>
                              <o>
                                <v n="Id">7129L</v>
                                <n n="Tag" />
                                <v n="Text">""</v>
                              </o>
                              <o>
                                <v n="Id">7081L</v>
                                <n n="Tag" />
                                <v n="Text">"END_IF"</v>
                              </o>
                            </a>
                          </o>
                        </o>
                        <v n="Id">7095L</v>
                      </o>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">true</v>
                      <v n="Id">7096L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">6723L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" />
                  <l2 n="Connectors" />
                  <v n="Id">5L</v>
                </o>
              </l2>
              <v n="BranchCounter">0</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
            <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
            <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
            <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
            <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
            <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
            <Type n="STImplementationObject">{3b83b776-fb25-43b8-99f2-3c507c9143fc}</Type>
            <Type n="String">System.String</Type>
            <Type n="STSnippet">{b2131366-6917-4304-87a9-64c0585560a8}</Type>
            <Type n="TextDocument">{f3878285-8e4f-490b-bb1b-9acbb7eb04db}</Type>
            <Type n="TextLine">{a5de0b0b-1cb5-4913-ac21-9d70293ec00d}</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
  </POU>
</TcPlcObject>